### ISSUE TITLE
Does this support throttling?

### ISSUE THREAD

**Issue by bauerjj** [Kryptonit3/Counter#6]
For instance, if a single user refreshed the page, would this extensions still increment the count for that particular page?

**Comment by Kryptonit3-zz** [comment]
This is a one hit quit type of package. Once a user hits the page in question, they will only increase it that one time. I will also add that because this package relies heavily on a "forever" cookie, that if the same user were to use a different browser, or clear browser cookies or use incognito mode it would count as a new user because the package cannot detect the cookie.

I am open to suggestions for more precise tracking of visitors and ways to prevent abuse.
